# Tokyo Night Starship - Hypernova Edition
# Futuristic, high-contrast, gradient prompt with deep-space aesthetics.

format = """
[](#1a1b26)\
$username$hostname\
[](fg:#1a1b26 bg:#3d59a1)\
$directory\
[](fg:#3d59a1 bg:#7aa2f7)\
$git_branch\
$git_status\
[](fg:#7aa2f7 bg:#bb9af7)\
$nodejs\
$rust\
$golang\
$python\
[](fg:#bb9af7 bg:#f7768e)\
$docker_context\
[](fg:#f7768e bg:#ff5e9c)\
$cmd_duration\
[](fg:#ff5e9c bg:#0f0c1d)\
$time\
[](#0f0c1d)
\n$character"""

[character]
success_symbol = "[➜](bold #7aa2f7)"
error_symbol = "[✗](bold #f7768e)"
vicmd_symbol = "[](bold #bb9af7)"
format = "$symbol "

[username]
style_user = "bg:#1a1b26 fg:#c0caf5"
style_root = "bg:#1a1b26 fg:#f7768e"
format = "[  $user ]($style)"
show_always = true

[directory]
style = "bg:#3d59a1 fg:#c8d3f5"
format = "[  $path ]($style)"
truncation_length = 3
truncation_symbol = "…/"
read_only = " "
read_only_style = "bg:#3d59a1 fg:#f7768e"

[git_branch]
symbol = ""
style = "bg:#7aa2f7 fg:#1a1b26"
format = "[ $symbol $branch ]($style)"

[git_status]
style = "bg:#7aa2f7 fg:#1a1b26"
format = "[ $all_status$ahead_behind ]($style)"

[nodejs]
symbol = ""
style = "bg:#bb9af7 fg:#1a1b26"
format = "[ $symbol $version ]($style)"

[rust]
symbol = ""
style = "bg:#bb9af7 fg:#1a1b26"
format = "[ $symbol $version ]($style)"

[golang]
symbol = ""
style = "bg:#bb9af7 fg:#1a1b26"
format = "[ $symbol $version ]($style)"

[python]
symbol = ""
style = "bg:#bb9af7 fg:#1a1b26"
format = "[ $symbol $version ]($style)"

[docker_context]
symbol = ""
style = "bg:#f7768e fg:#0f0c1d"
format = "[ $symbol $context ]($style)"

[time]
disabled = false
time_format = "%H:%M:%S"
style = "bg:#0f0c1d fg:#8be9fd"
format = "[ 󱑆 $time ]($style)"

[cmd_duration]
min_time = 1000
style = "bg:#ff5e9c fg:#0f0c1d"
format = "[  $duration ]($style)"

[hostname]
ssh_only = false
format = "[ $hostname ](bold bg:#1a1b26 fg:#bb9af7)"

